package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedHeader = `-- Code generated by tools/genstubs. DO NOT EDIT.
-- Regenerate with: make stubs
`

// emit writes all stub files into cfg.outDir.
func emit(cfg *config, regs *registrations, actions []string, closure *typeCloser, ovr *overrides) error {
	if err := emitGlobals(cfg, regs); err != nil {
		return err
	}
	if err := emitAliases(cfg, actions); err != nil {
		return err
	}
	if err := emitHooks(cfg, actions); err != nil {
		return err
	}
	for _, mod := range regs.modules {
		if err := emitModule(cfg, mod, closure, ovr); err != nil {
			return err
		}
	}
	for _, c := range closure.orderedClasses() {
		if err := emitClass(cfg, c, ovr); err != nil {
			return err
		}
	}
	return nil
}

func writeFile(path, body string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

func emitGlobals(cfg *config, regs *registrations) error {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("---@meta _\n\n")
	b.WriteString("---Imports a micro plugin module by Lua path.\n")
	b.WriteString("---@param pkg string\n")
	b.WriteString("---@return any\n")
	for _, mod := range regs.modules {
		fmt.Fprintf(&b, "---@overload fun(pkg: %q): %s\n",
			mod.luaPath, luaModuleClass(mod.luaPath))
	}
	b.WriteString("function import(pkg) end\n")
	return writeFile(filepath.Join(cfg.outDir, "_globals.lua"), b.String())
}

func emitAliases(cfg *config, actions []string) error {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("---@meta _\n\n")

	// Action verbs as a string-literal union.
	b.WriteString("---@alias ActionName\n")
	for i, a := range actions {
		sep := "---|"
		if i == len(actions)-1 {
			sep = "---|"
		}
		fmt.Fprintf(&b, "%s%q\n", sep, a)
	}
	b.WriteString("\n")

	// Integer-enum aliases for the BT*/MT*/RT* constants. BufType is
	// deliberately omitted: it's a struct on the Go side, and the
	// closure walker emits a proper @class for it.
	b.WriteString("---@alias MessageType integer\n")
	b.WriteString("---@alias RTFiletype integer\n")
	b.WriteString("---@alias OptionValue string|number|boolean\n")
	return writeFile(filepath.Join(cfg.outDir, "_aliases.lua"), b.String())
}

func emitHooks(cfg *config, actions []string) error {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("---@meta _\n\n")
	b.WriteString("-- Plugin lifecycle and event hooks. Define any of these as a global\n")
	b.WriteString("-- function in your plugin to receive the corresponding event. For pre-\n")
	b.WriteString("-- hooks, return false to cancel the action.\n\n")

	type hook struct {
		name string
		sig  string
		doc  string
	}
	var hs []hook
	hs = append(hs,
		hook{"init", "fun()", "Called once when the plugin is loaded."},
		hook{"preinit", "fun()", "Called before plugin initialization."},
		hook{"postinit", "fun()", "Called after all plugins finish loading."},
		hook{"deinit", "fun()", "Called when the plugin is unloaded."},
		hook{"onBufferOpen", "fun(buf: Buffer)", "Called when a buffer is opened."},
		hook{"onBufferOptionChanged", "fun(buf: Buffer, option: string, oldValue: any, newValue: any)",
			"Called when a buffer-local option changes."},
		hook{"onBeforeTextEvent", "fun(buf: Buffer, evt: any): boolean?",
			"Called before a text-modifying event is applied. Return false to cancel."},
		hook{"onBufPaneOpen", "fun(bp: BufPane)", "Called when a buffer pane is created."},
		hook{"onSetActive", "fun(bp: BufPane)", "Called when a pane becomes active."},
	)
	for _, a := range actions {
		hs = append(hs,
			hook{
				name: "pre" + a,
				sig:  "fun(bp: BufPane): boolean?",
				doc:  "Called before the " + a + " action runs. Return false to cancel.",
			},
			hook{
				name: "on" + a,
				sig:  "fun(bp: BufPane)",
				doc:  "Called after the " + a + " action runs.",
			},
		)
	}

	for _, h := range hs {
		fmt.Fprintf(&b, "---%s\n---@type %s\n%s = nil\n\n", h.doc, h.sig, h.name)
	}
	return writeFile(filepath.Join(cfg.outDir, "_hooks.lua"), b.String())
}

func emitModule(cfg *config, mod *moduleRegistrations, closure *typeCloser, ovr *overrides) error {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("---@meta _\n\n")

	className := luaModuleClass(mod.luaPath)
	fmt.Fprintf(&b, "---Module bound by import(%q).\n", mod.luaPath)
	fmt.Fprintf(&b, "---@class %s\n", className)
	for _, e := range mod.entries {
		typ := luaTypeOf(e.goType, closure, ovr)
		fmt.Fprintf(&b, "---@field %s %s\n", e.name, typ)
	}
	fmt.Fprintf(&b, "local M = {}\n\nreturn M\n")
	return writeFile(filepath.Join(cfg.outDir, luaModuleFile(mod.luaPath)), b.String())
}

func emitClass(cfg *config, rec *classRecord, ovr *overrides) error {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("---@meta _\n\n")

	header := "---@class " + rec.name
	if len(rec.embedded) > 0 {
		// LuaCATS only models single inheritance well; pick the first
		// embedded type as the parent and note the rest as a comment.
		sort.Strings(rec.embedded)
		header += " : " + rec.embedded[0]
		if len(rec.embedded) > 1 {
			b.WriteString("-- Also flattens (Go embeds): " + strings.Join(rec.embedded[1:], ", ") + "\n")
		}
	}
	fmt.Fprintln(&b, header)

	for _, f := range rec.fields {
		fmt.Fprintf(&b, "---@field %s %s\n", f.name, f.typ)
	}
	for _, line := range ovr.extraFields(rec.name) {
		fmt.Fprintf(&b, "---@field %s\n", line)
	}
	fmt.Fprintf(&b, "local %s = {}\n\n", rec.name)

	for _, m := range rec.methods {
		if ovr.skipMethod(rec.name, m.name) {
			continue
		}
		fmt.Fprintf(&b, "---@type %s\n%s.%s = nil\n\n", m.sig, rec.name, m.name)
	}

	fmt.Fprintf(&b, "return %s\n", rec.name)
	return writeFile(filepath.Join(cfg.outDir, classFile(rec.name)), b.String())
}

func classFile(name string) string {
	// Lower-case + .lua, e.g. "BufPane" -> "bufpane.lua".
	return strings.ToLower(name) + ".lua"
}
